### PR TITLE
🐛 Restore behavior of ignoring scorecard runtime errors

### LINKED ISSUE #269: E2e tests improvements
- [ ] Re-use existing issue instead of creating new one (Disable gostaging until this is done: we're inundated with issues otherwise)
- [x] Verify push/dispatch_workflow work properly
- [ ] Auto-close issues when e2e tests pass
- [x] Fix the content which contains `\n` instead of displaying a new line
- [x] Links to workflow files are broken
- [x] Provide the token type in the issue description (PAT or GITHUB_TOKEN)

### PR DESCRIPTION
**Pull request by spencerschrock**
This is a proper fix for #856.

As of [scorecard v4.7.0](https://github.com/ossf/scorecard/releases/tag/v4.7.0), runtime errors encountered during checks now produce a `ErrorCheckRuntime` error. These errors could be expected, for example repos with branch protection enabled but did not provide a PAT (currently a known limitation of scorecard). Or they could be from unexpected conditions / secondary rate limits.

These errors started bubbling up in scorecard v4.6.0, and while this was beneficial for CLI users of scorecard it broke the existing behavior of scorecard-action. To restore the behavior, scorecard-action now checks for these specific scorecard errors and continues to silently ignore them. 

e2e tests which would have caught #856 have been added in github.com/ossf-tests/scorecard-action-branch-protection-e2e
This also resolves #269

### CODE REVIEW

File: entrypoint/entrypoint.go [hunk 1]
```diff
@@ -78,6 +79,17 @@ func New() (*cobra.Command, error) {
...
 
+	// wrap scorecard's existing RunE, but ignore runtime errors that occur during checks
+	// users were having action failures due to secondary rate limits causing checks to fail
+	scorecardRunE := actionCmd.RunE
+	actionCmd.RunE = func(cmd *cobra.Command, args []string) error {
+		err := scorecardRunE(cmd, args)
+		if errors.Is(err, sce.ErrorCheckRuntime) {
+			err = nil
+		}
+		return err
```
Comment (azeemshaikh38) [inline entrypoint/entrypoint.go:90]: Nit:

```
if err := scorecardRunE(cmd, args); err != nil && !errors.Is(err, sce.ErrorcheckRuntime) {
  return err
}
return nil
```

**Review by azeemshaikh38 — APPROVED** [review]
Thanks!
