### PR TITLE
fix result file path issues

### LINKED ISSUE #1426: Failing e2e tests - scorecard-head on ossf-tests/scorecard-action
Matrix: null
Repo: https://github.com/ossf-tests/scorecard-action/tree/main
Run: https://github.com/ossf-tests/scorecard-action/actions/runs/10328319494
Workflow name: scorecard-head
Workflow file: https://github.com/ossf-tests/scorecard-action/tree/main/.github/workflows/scorecards-head.yml
Trigger: schedule
Branch: main

### LINKED ISSUE #1427: Failing e2e tests - scorecard-head on ossf-tests/scorecard-action
Matrix: null
Repo: https://github.com/ossf-tests/scorecard-action/tree/main
Run: https://github.com/ossf-tests/scorecard-action/actions/runs/10336410653
Workflow name: scorecard-head
Workflow file: https://github.com/ossf-tests/scorecard-action/tree/main/.github/workflows/scorecards-head.yml
Trigger: schedule
Branch: main

### LINKED ISSUE #1429: Failing e2e tests - scorecard-head on ossf-tests/scorecard-action
Matrix: null
Repo: https://github.com/ossf-tests/scorecard-action/tree/main
Run: https://github.com/ossf-tests/scorecard-action/actions/runs/10345047441
Workflow name: scorecard-head
Workflow file: https://github.com/ossf-tests/scorecard-action/tree/main/.github/workflows/scorecards-head.yml
Trigger: schedule
Branch: main

### PR DESCRIPTION
**Pull request by spencerschrock**
There were two issues at play that prevented the binary from reading the correct results file:

1. The paths were not joined with a separator during the refactor in #1423. This led to file not found errors, as the file was saved in the wrong directory, with the wrong name.
2. The signing code tried to read the file from the working directory instead of the GitHub workspace directory.

I was able to test this code after modifying the testing command in the `Dockerfile` to use a different `GITHUB_WORKSPACE` directory. The signing portion of the code will need to wait until the e2e test to confirm the fix.

We should eventually improve the [testing instructions](https://github.com/ossf/scorecard-action/blob/ab9729375aeb5f298cbbdcf9167c9fd974416537/Dockerfile#L15-L23), but at least the e2e test we have now caught this (via #1426 and #1427):
```shell
docker run -e GITHUB_REF=refs/heads/main \
     -e GITHUB_EVENT_NAME=branch_protection_rule \
    -e INPUT_RESULTS_FORMAT=json \
    -e INPUT_RESULTS_FILE=results.json \
    -e GITHUB_WORKSPACE="/home/runner/work/spencerschrock/actions-test" \
    -e INPUT_POLICY_FILE="/policy.yml" \
    -e INPUT_REPO_TOKEN=$GITHUB_AUTH_TOKEN \
    -e GITHUB_REPOSITORY="spencerschrock/actions-test" \
    -e GITHUB_EVENT_PATH="/event.json" \
    -e GITHUB_API_URL="https://api.github.com" \
    -e INPUT_PUBLISH_RESULTS="true" \
    -v /tmp/docker:/home/runner/work/spencerschrock/actions-test \
    spencerschrock/scorecard-action:latest
```

Fixes #1426
Fixes #1427
Fixes #1429

### CODE REVIEW

File: internal/scorecard/format.go [hunk 1]
```diff
@@ -45,7 +45,7 @@ func Format(result *scorecard.Result, opts *options.Options) error {
 	}
 
 	// write results to both stdout and result file
-	resultFile, err := os.Create(opts.GithubWorkspace + opts.InputResultsFile)
+	resultFile, err := os.Create(opts.GithubWorkspace + "/" + opts.InputResultsFile)
```
Comment (justaugustus) [inline internal/scorecard/format.go:48]: Maybe `filepath.Join` here instead?

**Review by justaugustus — CHANGES_REQUESTED** [review]
Quick nit!

File: internal/scorecard/format.go (hunk 1 above)
Comment (spencerschrock) [reply internal/scorecard/format.go]: Done, thanks for the suggestion.

**Review by justaugustus — APPROVED** [review]
Thanks for the quick fix, @spencerschrock!
